Feature/wewillcallyou.new
KarpenkoOleksandr/project-VegStore pull request #6
Opened 2023-07-01 18:23 UTC by KMIS2008

Полная мобильная версия

2023-07-02 08:00 UTC, KarpenkoOleksandr reviewed
1) кнопка Recall в макеті не має бордеруі перекриває бордер інпуту,
2) при введенні в інпут всіляких цифр і букв все відправляється по натисканню на кнопку.

2023-07-02 08:37 UTC, Andrij-Panasenko commented
Також треба забрати чорний бордер з кнопки
І задати інпуту required щоб не можна було відправити пусте поле

2023-07-02 09:08 UTC, Andrij-Panasenko requested changes
.

2023-07-02 12:27 UTC, KarpenkoOleksandr reviewed
Підправити хедер та параграф, розібратись із зображенням дівчини на десктоп версії.

2023-07-03 12:22 UTC, KarpenkoOleksandr approved these changes
approve.

2023-07-03 15:56 UTC, Andrij-Panasenko approved these changes
Approved

2023-07-03 15:56 UTC, merged