steps done
KarpenkoOleksandr/project-VegStore pull request #7
Opened 2023-07-02 09:13 UTC by alina513

Зроблена секція

2023-07-02 09:54 UTC, Andrij-Panasenko requested changes
Залишив коменти в повідомлення в Слак
Марджин крайніх елементів 
І центрування цифр в кружечках

2023-07-02 11:50 UTC, alina513 commented
Віправлено

2023-07-02 12:41 UTC, KarpenkoOleksandr requested changes
Треба змінити розмірі обгортки та контейнеру на 375px, бо стрибає при переході з 374 на 375px.

2023-07-02 13:15 UTC, alina513 commented
Все виправила

2023-07-02 15:02 UTC, alina513 commented
Виправила

2023-07-03 11:30 UTC, KarpenkoOleksandr requested changes
все ок, лише зроби правильний падинг у десктопі від заголовку. Скинув скрін в  Слек.

2023-07-03 11:50 UTC, alina513 commented
Переробила

2023-07-03 12:16 UTC, KarpenkoOleksandr approved these changes
approve.

2023-07-03 15:52 UTC, Andrij-Panasenko approved these changes
Checked
Approved

2023-07-03 15:54 UTC, merged